const axes_commands = [
  {
    description: 'Forward (Pitch)',
    notes: 'Joystick direction for moving forward',
    value: 'forward',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'Backward (Pitch)',
    notes: 'Joystick direction for moving backward',
    value: 'backward',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'Left (Roll)',
    notes: 'Joystick direction for moving to the left',
    value: 'left',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'Right (Roll)',
    notes: 'Joystick direction for moving to the right',
    value: 'right',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'Up',
    notes: 'Joystick direction for moving Up',
    value: 'up',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'Down',
    notes: 'Joystick direction for moving Down',
    value: 'down',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'CW (Yaw)',
    notes: 'Joystick direction to rotate clockwise',
    value: 'cw',
    type: 'axe',
    required: true,
    priority: 3,
  },
  {
    description: 'CCW (Yaw)',
    notes: 'Joystick direction to rotate counter clockwise',
    value: 'ccw',
    type: 'axe',
    required: true,
    priority: 3,
  },
];
const commands_buttons = [
  {
    description: 'Inintiate Command Mode',
    notes: 'Required before sending drone commands',
    value: 'command',
    type: 'button',
    required: true,
    priority: 3,
  },
  {
    description: 'Inintiate Video Broadcast',
    notes: 'Required for video streaming',
    value: 'streamon',
    type: 'button',
    required: false,
    priority: 3,
  },
  {
    description: 'Start Drone motors and takeoff',
    notes: 'Takeoff and go to ~60-90 cm height',
    value: 'takeoff',
    type: 'button',
    required: true,
    priority: 3,
  },
  {
    description: 'Land the Drone and stop the motors',
    notes: '~50cm/s land speed',
    value: 'land',
    type: 'button',
    required: true,
    priority: 1,
  },
  {
    description: 'Use for emergency stop',
    notes: 'Stop motors',
    value: 'emergency',
    type: 'button',
    required: true,
    priority: 1,
  },
  {
    description: 'Flip drone to the left',
    notes: 'Battery and height restrictions',
    value: 'flip l',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 2,
  },
  {
    description: 'Flip drone to the right',
    notes: 'Battery and height restrictions',
    value: 'flip r',
    type: 'button',
    required: false,
    priority: 2,
  },
  {
    description: 'Flip drone forward',
    notes: 'Battery and height restrictions',
    value: 'flip f',
    type: 'button',
    required: false,
    priority: 2,
  },
  {
    description: 'Flip drone backwards',
    notes: 'Battery and height restrictions',
    value: 'flip b',
    type: 'button',
    required: false,
    priority: 2,
  },
  {
    description: 'Set Speed to 100',
    notes: 'Set Speed to 100',
    value: 'speed 100',
    type: 'button',
    required: false,
    priority: 3,
  },
  {
    description: 'Set Speed to 75',
    notes: 'Set Speed to 75',
    value: 'speed 75',
    type: 'button',
    required: false,
    priority: 3,
  },
  {
    description: 'Set Speed to 50',
    notes: 'Set Speed to 50',
    value: 'speed 50',
    type: 'button',
    required: false,
    priority: 3,
  },
  {
    description: 'Set Speed to 25',
    notes: 'Set Speed to 25',
    value: 'speed 25',
    type: 'button',
    required: false,
    priority: 3,
  },
  /*
  {
    description: 'Go up 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'up x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go down 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'down x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go left 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'left x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go right 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'right x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go forward 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'forward x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go backward 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'back x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Go backward 20 - 500',
    notes: 'Centimeters - Imput lower than 20 will get ignored',
    value: 'back x',
    type: 'range',
    min: 20,
    max: 500,
    required: false,
    priority: 3
  },
  {
    description: 'Rotate drone clockwise 1-360',
    notes: 'Degrees',
    value: 'cw x',
    type: 'range',
    min: 1,
    max: 360,
    required: false,
    priority: 3
  },
  {
    description: 'Rotate drone counter clockwise 1-360',
    notes: 'Degrees',
    value: 'ccw x',
    type: 'range',
    min: 1,
    max: 360,
    required: false,
    priority: 3
  },
  */
];
export { commands_buttons, axes_commands };
